"""Update movie, gallery, trailer models

Revision ID: 25770702c679
Revises: fc7a28deb8ed
Create Date: 2026-02-18 10:55:40.690417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25770702c679'
down_revision = 'fc7a28deb8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_title', sa.String(length=200), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('pricing_type', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rental_duration', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('movie_file', sa.String(length=255), nullable=False),
    sa.Column('poster_file', sa.String(length=255), nullable=False),
    sa.Column('trailer_file', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('add_watermark', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('image_files', sa.Text(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trailer_type', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('trailer_file', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_file', sa.String(length=255), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project')
    op.drop_table('gallery_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=255), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('original_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pricing_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('rental_duration', sa.INTEGER(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('movie_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('poster_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('trailer_file', sa.VARCHAR(length=255), nullable=True),
    sa.Column('thumbnail_file', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trailer')
    op.drop_table('gallery')
    op.drop_table('movie')
    # ### end Alembic commands ###
