"""Add portfolio activities table

Revision ID: 2848d839ab1d
Revises: d420b0034ee5
Create Date: 2026-02-21 11:43:20.167001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2848d839ab1d'
down_revision = 'd420b0034ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_activities', schema=None) as batch_op:
        batch_op.create_index('idx_item_lookup', ['item_id', 'item_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_activities', schema=None) as batch_op:
        batch_op.drop_index('idx_item_lookup')

    op.drop_table('portfolio_activities')
    # ### end Alembic commands ###
