"""create project table

Revision ID: 6aaed60a2c7b
Revises: 52c7f27e04fb
Create Date: 2026-02-16 23:54:42.663640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aaed60a2c7b'
down_revision = '52c7f27e04fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pricing_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rental_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('movie_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trailer_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_file', sa.String(length=255), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('thumbnail_file')
        batch_op.drop_column('trailer_file')
        batch_op.drop_column('poster_file')
        batch_op.drop_column('movie_file')
        batch_op.drop_column('release_date')
        batch_op.drop_column('language')
        batch_op.drop_column('rental_duration')
        batch_op.drop_column('price')
        batch_op.drop_column('pricing_type')
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_title')

    # ### end Alembic commands ###
