"""Add target_type to UserActivity

Revision ID: 9c3f4ad0d9ad
Revises: f6779e9d1efe
Create Date: 2026-03-10 01:34:09.915108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3f4ad0d9ad'
down_revision = 'f6779e9d1efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
