"""add show_in_services to movie

Revision ID: 9f7b90b8a5a8
Revises: 2848d839ab1d
Create Date: 2026-03-01 11:08:32.433299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7b90b8a5a8'
down_revision = '2848d839ab1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_services', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('show_in_services')

    # ### end Alembic commands ###
