"""add email column to user

Revision ID: c3ef824b2ba8
Revises: 81409611ac6c
Create Date: 2026-03-07 12:37:39.709329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ef824b2ba8'
down_revision = '81409611ac6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Step 1: Add column as nullable
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # Step 2: Optionally set a default email for existing users
    op.execute('UPDATE "user" SET email = username || \'@example.com\' WHERE email IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Step 3: Make the column non-nullable and unique
        batch_op.alter_column('email', nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###