"""empty message

Revision ID: f6779e9d1efe
Revises: 904efa3da841
Create Date: 2026-03-09 23:26:28.765999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6779e9d1efe'
down_revision = '904efa3da841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=200), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_activities', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('user_activity')
    # ### end Alembic commands ###
